const portfolioProjects = [
  {
    id: 1,
    name: "달달",
    category: "소셜 네트워킹",
    description:
      "슈퍼 데이트 신청권을 통한 진정한 만남을 시작하는 소셜 네트워킹 플랫폼",
    image: "/images/daldal.png",
    url: "https://daldal.vercel.app",
    features: [
      "익명 투표 시스템",
      "상호 선택 매칭",
      "1:1 데이트 진행",
      "커뮤니티 운영",
    ],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.9,
    views: 2156,
    isCompleted: true,
  },
  {
    id: 2,
    name: "산카쿠",
    category: "음식 & 다이닝",
    description:
      "정통 일본 라멘의 맛을 그대로 담은 특별한 식사 경험을 제공하는 레스토랑 웹사이트",
    image: "/images/sankaku.png",
    url: "https://sankaku-steel.vercel.app",
    features: ["메뉴 소개", "매장 안내", "브랜드 스토리", "창업 문의"],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.8,
    views: 1890,
    isCompleted: false,
  },
  {
    id: 3,
    name: "VIX Academy",
    category: "교육",
    description:
      "아이들의 미래를 위한 최고의 영어 교육을 제공하는 교육 기관 웹사이트",
    image: "/images/vixAcademy.png",
    url: "https://www.vix.academy",
    features: ["교육 프로그램 소개", "상담 신청", "시설 안내", "STEAM 교육"],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.9,
    views: 3240,
    isCompleted: true,
  },
  {
    id: 4,
    name: "Only Vocal Academy",
    category: "교육",
    description:
      "보컬 교육 전문 아카데미의 웹사이트로 수강 신청과 커리큘럼 소개",
    image: "/images/onlyVocal.png",
    url: "https://only-vocal-academy.vercel.app",
    features: ["보컬 교육 프로그램", "수강 신청", "강사 소개", "커리큘럼 안내"],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.7,
    views: 1567,
    isCompleted: false,
  },
  {
    id: 5,
    name: "한소망교회",
    category: "종교 & 교회",
    description: "하나님의 사랑과 소망을 전하는 교회의 공식 웹사이트",
    image: "/images/hanSoMangChurch.png",
    url: "https://han-so-mang-church-duam.vercel.app",
    features: [
      "예배 시간표",
      "교회 소개",
      "부서별 사역",
      "온라인 헌금",
      "소식 & 일정",
    ],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.8,
    views: 1890,
    isCompleted: false,
  },
  {
    id: 6,
    name: "산카쿠 프랜차이즈 랜딩페이지",
    category: "음식 & 다이닝",
    description: "산카쿠 프랜차이즈 가맹점 문의 사이트",
    image: "/images/sankaku-franchise-landing-page.png",
    url: "https://sankaku-franchise-landing-page.vercel.app/",
    features: ["창업성공사례", "성공브랜드", "매출증명", "메뉴안내"],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.8,
    views: 2000,
    isCompleted: false,
  },
  {
    id: 7,
    name: "술개팅",
    category: "소셜 네트워킹",
    description: "로테이션 소개팅 플랫폼",
    image: "/images/sulgaeting.png",
    url: "https://sulgaeting.com/",
    features: [
      "익명 투표 시스템",
      "상호 선택 매칭",
      "1:1 데이트 진행",
      "커뮤니티 운영",
    ],
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    rating: 4.8,
    views: 2000,
    isCompleted: false,
  },
];

export default portfolioProjects;
